# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/UI_640x480.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 641, 441))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Main = QtGui.QWidget()
        self.tab_Main.setObjectName(_fromUtf8("tab_Main"))
        self.progressBar_RFout_FWD = QtGui.QProgressBar(self.tab_Main)
        self.progressBar_RFout_FWD.setGeometry(QtCore.QRect(545, 85, 81, 281))
        self.progressBar_RFout_FWD.setMaximum(3000)
        self.progressBar_RFout_FWD.setProperty("value", 2400)
        self.progressBar_RFout_FWD.setTextVisible(False)
        self.progressBar_RFout_FWD.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_FWD.setInvertedAppearance(False)
        self.progressBar_RFout_FWD.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_RFout_FWD.setObjectName(_fromUtf8("progressBar_RFout_FWD"))
        self.pushButton_RFon = QtGui.QPushButton(self.tab_Main)
        self.pushButton_RFon.setEnabled(True)
        self.pushButton_RFon.setGeometry(QtCore.QRect(10, 10, 241, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 231, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 231, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 231, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.pushButton_RFon.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RFon.setFont(font)
        self.pushButton_RFon.setCheckable(True)
        self.pushButton_RFon.setFlat(False)
        self.pushButton_RFon.setObjectName(_fromUtf8("pushButton_RFon"))
        self.progressBar_RFout_REF = QtGui.QProgressBar(self.tab_Main)
        self.progressBar_RFout_REF.setGeometry(QtCore.QRect(455, 85, 81, 281))
        self.progressBar_RFout_REF.setProperty("value", 24)
        self.progressBar_RFout_REF.setTextVisible(False)
        self.progressBar_RFout_REF.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_REF.setInvertedAppearance(False)
        self.progressBar_RFout_REF.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_RFout_REF.setObjectName(_fromUtf8("progressBar_RFout_REF"))
        self.progressBar_VSWR = QtGui.QProgressBar(self.tab_Main)
        self.progressBar_VSWR.setGeometry(QtCore.QRect(365, 85, 81, 281))
        self.progressBar_VSWR.setProperty("value", 24)
        self.progressBar_VSWR.setTextVisible(False)
        self.progressBar_VSWR.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_VSWR.setInvertedAppearance(False)
        self.progressBar_VSWR.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_VSWR.setObjectName(_fromUtf8("progressBar_VSWR"))
        self.label = QtGui.QLabel(self.tab_Main)
        self.label.setGeometry(QtCore.QRect(550, 370, 68, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_Main)
        self.label_2.setGeometry(QtCore.QRect(375, 370, 68, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_Reset = QtGui.QPushButton(self.tab_Main)
        self.pushButton_Reset.setEnabled(True)
        self.pushButton_Reset.setGeometry(QtCore.QRect(10, 95, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setCheckable(False)
        self.pushButton_Reset.setFlat(False)
        self.pushButton_Reset.setObjectName(_fromUtf8("pushButton_Reset"))
        self.label_3 = QtGui.QLabel(self.tab_Main)
        self.label_3.setGeometry(QtCore.QRect(465, 370, 68, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.progressBar_ETA = QtGui.QProgressBar(self.tab_Main)
        self.progressBar_ETA.setGeometry(QtCore.QRect(275, 85, 81, 281))
        self.progressBar_ETA.setProperty("value", 24)
        self.progressBar_ETA.setTextVisible(False)
        self.progressBar_ETA.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_ETA.setInvertedAppearance(False)
        self.progressBar_ETA.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_ETA.setObjectName(_fromUtf8("progressBar_ETA"))
        self.label_4 = QtGui.QLabel(self.tab_Main)
        self.label_4.setGeometry(QtCore.QRect(295, 370, 68, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_eta = QtGui.QLabel(self.tab_Main)
        self.label_eta.setGeometry(QtCore.QRect(275, 35, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_eta.setFont(font)
        self.label_eta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eta.setObjectName(_fromUtf8("label_eta"))
        self.label_VSWR = QtGui.QLabel(self.tab_Main)
        self.label_VSWR.setGeometry(QtCore.QRect(365, 35, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_VSWR.setFont(font)
        self.label_VSWR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_VSWR.setObjectName(_fromUtf8("label_VSWR"))
        self.label_RFout_REV = QtGui.QLabel(self.tab_Main)
        self.label_RFout_REV.setGeometry(QtCore.QRect(455, 35, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_REV.setFont(font)
        self.label_RFout_REV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_REV.setObjectName(_fromUtf8("label_RFout_REV"))
        self.label_RFout_FWD = QtGui.QLabel(self.tab_Main)
        self.label_RFout_FWD.setGeometry(QtCore.QRect(545, 35, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_FWD.setFont(font)
        self.label_RFout_FWD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_FWD.setObjectName(_fromUtf8("label_RFout_FWD"))
        self.tabWidget.addTab(self.tab_Main, _fromUtf8(""))
        self.tab_AMP1 = QtGui.QWidget()
        self.tab_AMP1.setObjectName(_fromUtf8("tab_AMP1"))
        self.tabWidget.addTab(self.tab_AMP1, _fromUtf8(""))
        self.tab_AMP2 = QtGui.QWidget()
        self.tab_AMP2.setObjectName(_fromUtf8("tab_AMP2"))
        self.tabWidget.addTab(self.tab_AMP2, _fromUtf8(""))
        self.tab_Setup = QtGui.QWidget()
        self.tab_Setup.setObjectName(_fromUtf8("tab_Setup"))
        self.label_Hostname = QtGui.QLabel(self.tab_Setup)
        self.label_Hostname.setGeometry(QtCore.QRect(14, 11, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Hostname.setFont(font)
        self.label_Hostname.setObjectName(_fromUtf8("label_Hostname"))
        self.lineEdit_Hostname = QtGui.QLineEdit(self.tab_Setup)
        self.lineEdit_Hostname.setGeometry(QtCore.QRect(150, 9, 450, 37))
        self.lineEdit_Hostname.setObjectName(_fromUtf8("lineEdit_Hostname"))
        self.tabWidget.addTab(self.tab_Setup, _fromUtf8(""))
        self.label_Status = QtGui.QLabel(self.centralwidget)
        self.label_Status.setGeometry(QtCore.QRect(0, 0, 641, 46))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Status.setFont(font)
        self.label_Status.setObjectName(_fromUtf8("label_Status"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RF AMP Interface", None))
        self.progressBar_RFout_FWD.setFormat(_translate("MainWindow", "%p kW", None))
        self.pushButton_RFon.setText(_translate("MainWindow", "RF off", None))
        self.progressBar_RFout_REF.setFormat(_translate("MainWindow", "%p kW", None))
        self.progressBar_VSWR.setFormat(_translate("MainWindow", "%p kW", None))
        self.label.setText(_translate("MainWindow", "RF-out\n"
"FWD", None))
        self.label_2.setText(_translate("MainWindow", "VSWR", None))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset", None))
        self.label_3.setText(_translate("MainWindow", "RF-out\n"
"REF", None))
        self.progressBar_ETA.setFormat(_translate("MainWindow", "%p kW", None))
        self.label_4.setText(_translate("MainWindow", "eta", None))
        self.label_eta.setText(_translate("MainWindow", "66%", None))
        self.label_VSWR.setText(_translate("MainWindow", "1 : 2.3", None))
        self.label_RFout_REV.setText(_translate("MainWindow", "0.4kW", None))
        self.label_RFout_FWD.setText(_translate("MainWindow", "2.4kW", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Main), _translate("MainWindow", "   Main   ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AMP1), _translate("MainWindow", "   AMP1   ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AMP2), _translate("MainWindow", "   AMP2   ", None))
        self.label_Hostname.setText(_translate("MainWindow", "Hostname: ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Setup), _translate("MainWindow", "   Setup   ", None))
        self.label_Status.setText(_translate("MainWindow", "Status Label", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

