# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/UI_640x480.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 641, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Main = QtWidgets.QWidget()
        self.tab_Main.setObjectName("tab_Main")
        self.progressBar_RFout_FOR = QtWidgets.QProgressBar(self.tab_Main)
        self.progressBar_RFout_FOR.setGeometry(QtCore.QRect(540, 80, 81, 281))
        self.progressBar_RFout_FOR.setMaximum(3000)
        self.progressBar_RFout_FOR.setProperty("value", 2400)
        self.progressBar_RFout_FOR.setTextVisible(False)
        self.progressBar_RFout_FOR.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_FOR.setInvertedAppearance(False)
        self.progressBar_RFout_FOR.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_RFout_FOR.setObjectName("progressBar_RFout_FOR")
        self.progressBar_RFout_REF = QtWidgets.QProgressBar(self.tab_Main)
        self.progressBar_RFout_REF.setGeometry(QtCore.QRect(450, 80, 81, 281))
        self.progressBar_RFout_REF.setMaximum(3000)
        self.progressBar_RFout_REF.setProperty("value", 400)
        self.progressBar_RFout_REF.setTextVisible(False)
        self.progressBar_RFout_REF.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_REF.setInvertedAppearance(False)
        self.progressBar_RFout_REF.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_RFout_REF.setObjectName("progressBar_RFout_REF")
        self.progressBar_VSWR = QtWidgets.QProgressBar(self.tab_Main)
        self.progressBar_VSWR.setGeometry(QtCore.QRect(360, 80, 81, 281))
        self.progressBar_VSWR.setMaximum(300)
        self.progressBar_VSWR.setProperty("value", 230)
        self.progressBar_VSWR.setTextVisible(False)
        self.progressBar_VSWR.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_VSWR.setInvertedAppearance(False)
        self.progressBar_VSWR.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_VSWR.setObjectName("progressBar_VSWR")
        self.label = QtWidgets.QLabel(self.tab_Main)
        self.label.setGeometry(QtCore.QRect(555, 365, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_Main)
        self.label_2.setGeometry(QtCore.QRect(370, 365, 68, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_Main)
        self.label_3.setGeometry(QtCore.QRect(475, 365, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.progressBar_ETA = QtWidgets.QProgressBar(self.tab_Main)
        self.progressBar_ETA.setGeometry(QtCore.QRect(270, 80, 81, 281))
        self.progressBar_ETA.setProperty("value", 66)
        self.progressBar_ETA.setTextVisible(False)
        self.progressBar_ETA.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_ETA.setInvertedAppearance(False)
        self.progressBar_ETA.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_ETA.setObjectName("progressBar_ETA")
        self.label_4 = QtWidgets.QLabel(self.tab_Main)
        self.label_4.setGeometry(QtCore.QRect(290, 365, 68, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_eta = QtWidgets.QLabel(self.tab_Main)
        self.label_eta.setGeometry(QtCore.QRect(270, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_eta.setFont(font)
        self.label_eta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eta.setObjectName("label_eta")
        self.label_VSWR = QtWidgets.QLabel(self.tab_Main)
        self.label_VSWR.setGeometry(QtCore.QRect(360, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_VSWR.setFont(font)
        self.label_VSWR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_VSWR.setObjectName("label_VSWR")
        self.label_RFout_REF = QtWidgets.QLabel(self.tab_Main)
        self.label_RFout_REF.setGeometry(QtCore.QRect(450, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_REF.setFont(font)
        self.label_RFout_REF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_REF.setObjectName("label_RFout_REF")
        self.label_RFout_FOR = QtWidgets.QLabel(self.tab_Main)
        self.label_RFout_FOR.setGeometry(QtCore.QRect(540, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_FOR.setFont(font)
        self.label_RFout_FOR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_FOR.setObjectName("label_RFout_FOR")
        self.frame_SumFault_statecontrol = QtWidgets.QFrame(self.tab_Main)
        self.frame_SumFault_statecontrol.setGeometry(QtCore.QRect(30, 20, 220, 361))
        self.frame_SumFault_statecontrol.setAutoFillBackground(True)
        self.frame_SumFault_statecontrol.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_SumFault_statecontrol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SumFault_statecontrol.setObjectName("frame_SumFault_statecontrol")
        self.label_FaultDetected = QtWidgets.QLabel(self.frame_SumFault_statecontrol)
        self.label_FaultDetected.setGeometry(QtCore.QRect(40, 100, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_FaultDetected.setFont(font)
        self.label_FaultDetected.setObjectName("label_FaultDetected")
        self.pushButton_OP = QtWidgets.QPushButton(self.tab_Main)
        self.pushButton_OP.setEnabled(True)
        self.pushButton_OP.setGeometry(QtCore.QRect(40, 270, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OP.setFont(font)
        self.pushButton_OP.setCheckable(True)
        self.pushButton_OP.setFlat(False)
        self.pushButton_OP.setObjectName("pushButton_OP")
        self.pushButton_PTT = QtWidgets.QPushButton(self.tab_Main)
        self.pushButton_PTT.setEnabled(True)
        self.pushButton_PTT.setGeometry(QtCore.QRect(40, 30, 200, 211))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_PTT.setFont(font)
        self.pushButton_PTT.setCheckable(True)
        self.pushButton_PTT.setFlat(False)
        self.pushButton_PTT.setObjectName("pushButton_PTT")
        self.pushButton_Reset = QtWidgets.QPushButton(self.tab_Main)
        self.pushButton_Reset.setEnabled(True)
        self.pushButton_Reset.setGeometry(QtCore.QRect(40, 320, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Reset.setFont(font)
        self.pushButton_Reset.setCheckable(False)
        self.pushButton_Reset.setFlat(False)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.frame_SumFault_statecontrol.raise_()
        self.progressBar_RFout_FOR.raise_()
        self.progressBar_RFout_REF.raise_()
        self.progressBar_VSWR.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.progressBar_ETA.raise_()
        self.label_4.raise_()
        self.label_eta.raise_()
        self.label_VSWR.raise_()
        self.label_RFout_REF.raise_()
        self.label_RFout_FOR.raise_()
        self.pushButton_OP.raise_()
        self.pushButton_PTT.raise_()
        self.pushButton_Reset.raise_()
        self.tabWidget.addTab(self.tab_Main, "")
        self.tab_AMP1 = QtWidgets.QWidget()
        self.tab_AMP1.setObjectName("tab_AMP1")
        self.label_5 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_5.setGeometry(QtCore.QRect(475, 365, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_6.setGeometry(QtCore.QRect(555, 365, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_7.setGeometry(QtCore.QRect(370, 365, 68, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.progressBar_ETA_Amp1 = QtWidgets.QProgressBar(self.tab_AMP1)
        self.progressBar_ETA_Amp1.setGeometry(QtCore.QRect(270, 80, 81, 281))
        self.progressBar_ETA_Amp1.setProperty("value", 66)
        self.progressBar_ETA_Amp1.setTextVisible(False)
        self.progressBar_ETA_Amp1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_ETA_Amp1.setInvertedAppearance(False)
        self.progressBar_ETA_Amp1.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_ETA_Amp1.setObjectName("progressBar_ETA_Amp1")
        self.label_8 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_8.setGeometry(QtCore.QRect(290, 365, 68, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.progressBar_RFout_FOR_Amp1 = QtWidgets.QProgressBar(self.tab_AMP1)
        self.progressBar_RFout_FOR_Amp1.setGeometry(QtCore.QRect(540, 80, 81, 281))
        self.progressBar_RFout_FOR_Amp1.setMaximum(3000)
        self.progressBar_RFout_FOR_Amp1.setProperty("value", 2400)
        self.progressBar_RFout_FOR_Amp1.setTextVisible(False)
        self.progressBar_RFout_FOR_Amp1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_FOR_Amp1.setInvertedAppearance(False)
        self.progressBar_RFout_FOR_Amp1.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_RFout_FOR_Amp1.setObjectName("progressBar_RFout_FOR_Amp1")
        self.label_VSWR_Amp1 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_VSWR_Amp1.setGeometry(QtCore.QRect(360, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_VSWR_Amp1.setFont(font)
        self.label_VSWR_Amp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_VSWR_Amp1.setObjectName("label_VSWR_Amp1")
        self.label_eta_Amp1 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_eta_Amp1.setGeometry(QtCore.QRect(250, 30, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_eta_Amp1.setFont(font)
        self.label_eta_Amp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eta_Amp1.setObjectName("label_eta_Amp1")
        self.label_RFout_REF_Amp1 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_RFout_REF_Amp1.setGeometry(QtCore.QRect(450, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_REF_Amp1.setFont(font)
        self.label_RFout_REF_Amp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_REF_Amp1.setObjectName("label_RFout_REF_Amp1")
        self.label_RFout_FOR_Amp1 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_RFout_FOR_Amp1.setGeometry(QtCore.QRect(540, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_FOR_Amp1.setFont(font)
        self.label_RFout_FOR_Amp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_FOR_Amp1.setObjectName("label_RFout_FOR_Amp1")
        self.progressBar_VSWR_Amp1 = QtWidgets.QProgressBar(self.tab_AMP1)
        self.progressBar_VSWR_Amp1.setGeometry(QtCore.QRect(360, 80, 81, 281))
        self.progressBar_VSWR_Amp1.setMaximum(300)
        self.progressBar_VSWR_Amp1.setProperty("value", 230)
        self.progressBar_VSWR_Amp1.setTextVisible(False)
        self.progressBar_VSWR_Amp1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_VSWR_Amp1.setInvertedAppearance(False)
        self.progressBar_VSWR_Amp1.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_VSWR_Amp1.setObjectName("progressBar_VSWR_Amp1")
        self.progressBar_RFout_REF_Amp1 = QtWidgets.QProgressBar(self.tab_AMP1)
        self.progressBar_RFout_REF_Amp1.setGeometry(QtCore.QRect(450, 80, 81, 281))
        self.progressBar_RFout_REF_Amp1.setMaximum(3000)
        self.progressBar_RFout_REF_Amp1.setProperty("value", 400)
        self.progressBar_RFout_REF_Amp1.setTextVisible(False)
        self.progressBar_RFout_REF_Amp1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_REF_Amp1.setInvertedAppearance(False)
        self.progressBar_RFout_REF_Amp1.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_RFout_REF_Amp1.setObjectName("progressBar_RFout_REF_Amp1")
        self.frame_VSWR_Amp1 = QtWidgets.QFrame(self.tab_AMP1)
        self.frame_VSWR_Amp1.setGeometry(QtCore.QRect(10, 60, 201, 41))
        self.frame_VSWR_Amp1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VSWR_Amp1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VSWR_Amp1.setObjectName("frame_VSWR_Amp1")
        self.label_13 = QtWidgets.QLabel(self.frame_VSWR_Amp1)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_AMP1)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.frame_Temp_Amp1 = QtWidgets.QFrame(self.tab_AMP1)
        self.frame_Temp_Amp1.setGeometry(QtCore.QRect(10, 100, 201, 41))
        self.frame_Temp_Amp1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Temp_Amp1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Temp_Amp1.setObjectName("frame_Temp_Amp1")
        self.label_16 = QtWidgets.QLabel(self.frame_Temp_Amp1)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_AMP1, "")
        self.tab_AMP2 = QtWidgets.QWidget()
        self.tab_AMP2.setObjectName("tab_AMP2")
        self.label_9 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_9.setGeometry(QtCore.QRect(555, 365, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_10.setGeometry(QtCore.QRect(370, 365, 68, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_eta_Amp1_2 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_eta_Amp1_2.setGeometry(QtCore.QRect(250, 30, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_eta_Amp1_2.setFont(font)
        self.label_eta_Amp1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_eta_Amp1_2.setObjectName("label_eta_Amp1_2")
        self.label_11 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_11.setGeometry(QtCore.QRect(475, 365, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_RFout_FOR_Amp1_2 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_RFout_FOR_Amp1_2.setGeometry(QtCore.QRect(540, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_FOR_Amp1_2.setFont(font)
        self.label_RFout_FOR_Amp1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_FOR_Amp1_2.setObjectName("label_RFout_FOR_Amp1_2")
        self.label_12 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_12.setGeometry(QtCore.QRect(290, 365, 68, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.progressBar_ETA_Amp1_2 = QtWidgets.QProgressBar(self.tab_AMP2)
        self.progressBar_ETA_Amp1_2.setGeometry(QtCore.QRect(270, 80, 81, 281))
        self.progressBar_ETA_Amp1_2.setProperty("value", 66)
        self.progressBar_ETA_Amp1_2.setTextVisible(False)
        self.progressBar_ETA_Amp1_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_ETA_Amp1_2.setInvertedAppearance(False)
        self.progressBar_ETA_Amp1_2.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_ETA_Amp1_2.setObjectName("progressBar_ETA_Amp1_2")
        self.progressBar_VSWR_Amp1_2 = QtWidgets.QProgressBar(self.tab_AMP2)
        self.progressBar_VSWR_Amp1_2.setGeometry(QtCore.QRect(360, 80, 81, 281))
        self.progressBar_VSWR_Amp1_2.setMaximum(300)
        self.progressBar_VSWR_Amp1_2.setProperty("value", 230)
        self.progressBar_VSWR_Amp1_2.setTextVisible(False)
        self.progressBar_VSWR_Amp1_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_VSWR_Amp1_2.setInvertedAppearance(False)
        self.progressBar_VSWR_Amp1_2.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_VSWR_Amp1_2.setObjectName("progressBar_VSWR_Amp1_2")
        self.progressBar_RFout_FOR_Amp1_2 = QtWidgets.QProgressBar(self.tab_AMP2)
        self.progressBar_RFout_FOR_Amp1_2.setGeometry(QtCore.QRect(540, 80, 81, 281))
        self.progressBar_RFout_FOR_Amp1_2.setMaximum(3000)
        self.progressBar_RFout_FOR_Amp1_2.setProperty("value", 2400)
        self.progressBar_RFout_FOR_Amp1_2.setTextVisible(False)
        self.progressBar_RFout_FOR_Amp1_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_FOR_Amp1_2.setInvertedAppearance(False)
        self.progressBar_RFout_FOR_Amp1_2.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_RFout_FOR_Amp1_2.setObjectName("progressBar_RFout_FOR_Amp1_2")
        self.progressBar_RFout_REF_Amp1_2 = QtWidgets.QProgressBar(self.tab_AMP2)
        self.progressBar_RFout_REF_Amp1_2.setGeometry(QtCore.QRect(450, 80, 81, 281))
        self.progressBar_RFout_REF_Amp1_2.setMaximum(3000)
        self.progressBar_RFout_REF_Amp1_2.setProperty("value", 400)
        self.progressBar_RFout_REF_Amp1_2.setTextVisible(False)
        self.progressBar_RFout_REF_Amp1_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RFout_REF_Amp1_2.setInvertedAppearance(False)
        self.progressBar_RFout_REF_Amp1_2.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_RFout_REF_Amp1_2.setObjectName("progressBar_RFout_REF_Amp1_2")
        self.label_VSWR_Amp1_2 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_VSWR_Amp1_2.setGeometry(QtCore.QRect(360, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_VSWR_Amp1_2.setFont(font)
        self.label_VSWR_Amp1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_VSWR_Amp1_2.setObjectName("label_VSWR_Amp1_2")
        self.label_RFout_REF_Amp1_2 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_RFout_REF_Amp1_2.setGeometry(QtCore.QRect(450, 30, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_RFout_REF_Amp1_2.setFont(font)
        self.label_RFout_REF_Amp1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RFout_REF_Amp1_2.setObjectName("label_RFout_REF_Amp1_2")
        self.frame_Temp_Amp2 = QtWidgets.QFrame(self.tab_AMP2)
        self.frame_Temp_Amp2.setGeometry(QtCore.QRect(10, 100, 201, 41))
        self.frame_Temp_Amp2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Temp_Amp2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Temp_Amp2.setObjectName("frame_Temp_Amp2")
        self.label_19 = QtWidgets.QLabel(self.frame_Temp_Amp2)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.frame_VSWR_Amp2 = QtWidgets.QFrame(self.tab_AMP2)
        self.frame_VSWR_Amp2.setGeometry(QtCore.QRect(10, 60, 201, 41))
        self.frame_VSWR_Amp2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VSWR_Amp2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VSWR_Amp2.setObjectName("frame_VSWR_Amp2")
        self.label_20 = QtWidgets.QLabel(self.frame_VSWR_Amp2)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_AMP2)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_AMP2, "")
        self.tab_System = QtWidgets.QWidget()
        self.tab_System.setObjectName("tab_System")
        self.label_Amplifier_Hostname = QtWidgets.QLabel(self.tab_System)
        self.label_Amplifier_Hostname.setGeometry(QtCore.QRect(10, 11, 611, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Amplifier_Hostname.setFont(font)
        self.label_Amplifier_Hostname.setObjectName("label_Amplifier_Hostname")
        self.label_Version = QtWidgets.QLabel(self.tab_System)
        self.label_Version.setGeometry(QtCore.QRect(10, 370, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Version.setFont(font)
        self.label_Version.setObjectName("label_Version")
        self.pushButton_emulateFault = QtWidgets.QPushButton(self.tab_System)
        self.pushButton_emulateFault.setEnabled(True)
        self.pushButton_emulateFault.setGeometry(QtCore.QRect(410, 220, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_emulateFault.setFont(font)
        self.pushButton_emulateFault.setCheckable(False)
        self.pushButton_emulateFault.setFlat(False)
        self.pushButton_emulateFault.setObjectName("pushButton_emulateFault")
        self.frame_VSWR_Amp1_2 = QtWidgets.QFrame(self.tab_System)
        self.frame_VSWR_Amp1_2.setGeometry(QtCore.QRect(410, 80, 201, 41))
        self.frame_VSWR_Amp1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VSWR_Amp1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VSWR_Amp1_2.setObjectName("frame_VSWR_Amp1_2")
        self.label_25 = QtWidgets.QLabel(self.frame_VSWR_Amp1_2)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.frame_VSWR_Amp1_3 = QtWidgets.QFrame(self.tab_System)
        self.frame_VSWR_Amp1_3.setGeometry(QtCore.QRect(410, 120, 201, 41))
        self.frame_VSWR_Amp1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VSWR_Amp1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VSWR_Amp1_3.setObjectName("frame_VSWR_Amp1_3")
        self.label_26 = QtWidgets.QLabel(self.frame_VSWR_Amp1_3)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.frame_VSWR_Amp1_4 = QtWidgets.QFrame(self.tab_System)
        self.frame_VSWR_Amp1_4.setGeometry(QtCore.QRect(410, 160, 201, 41))
        self.frame_VSWR_Amp1_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VSWR_Amp1_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VSWR_Amp1_4.setObjectName("frame_VSWR_Amp1_4")
        self.label_27 = QtWidgets.QLabel(self.frame_VSWR_Amp1_4)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.comboBox_BandSelect = QtWidgets.QComboBox(self.tab_System)
        self.comboBox_BandSelect.setGeometry(QtCore.QRect(10, 80, 311, 61))
        self.comboBox_BandSelect.setEditable(False)
        self.comboBox_BandSelect.setObjectName("comboBox_BandSelect")
        self.label_Version_2 = QtWidgets.QLabel(self.tab_System)
        self.label_Version_2.setGeometry(QtCore.QRect(10, 50, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Version_2.setFont(font)
        self.label_Version_2.setObjectName("label_Version_2")
        self.label_Version_3 = QtWidgets.QLabel(self.tab_System)
        self.label_Version_3.setGeometry(QtCore.QRect(420, 50, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Version_3.setFont(font)
        self.label_Version_3.setObjectName("label_Version_3")
        self.label_Version_4 = QtWidgets.QLabel(self.tab_System)
        self.label_Version_4.setGeometry(QtCore.QRect(10, 170, 181, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Version_4.setFont(font)
        self.label_Version_4.setObjectName("label_Version_4")
        self.comboBox_AntennaSelect = QtWidgets.QComboBox(self.tab_System)
        self.comboBox_AntennaSelect.setGeometry(QtCore.QRect(10, 200, 311, 61))
        self.comboBox_AntennaSelect.setObjectName("comboBox_AntennaSelect")
        self.tabWidget.addTab(self.tab_System, "")
        self.frame_SumFault_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_SumFault_header.setGeometry(QtCore.QRect(0, 0, 651, 31))
        self.frame_SumFault_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SumFault_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SumFault_header.setObjectName("frame_SumFault_header")
        self.label_Status = QtWidgets.QLabel(self.frame_SumFault_header)
        self.label_Status.setGeometry(QtCore.QRect(0, 0, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Status.setFont(font)
        self.label_Status.setObjectName("label_Status")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RF AMP Interface"))
        self.progressBar_RFout_FOR.setFormat(_translate("MainWindow", "%p kW"))
        self.progressBar_RFout_REF.setFormat(_translate("MainWindow", "%p kW"))
        self.progressBar_VSWR.setFormat(_translate("MainWindow", "%p kW"))
        self.label.setText(_translate("MainWindow", "FOR"))
        self.label_2.setText(_translate("MainWindow", "VSWR"))
        self.label_3.setText(_translate("MainWindow", "REF"))
        self.progressBar_ETA.setFormat(_translate("MainWindow", "%p kW"))
        self.label_4.setText(_translate("MainWindow", "eta"))
        self.label_eta.setText(_translate("MainWindow", "66%"))
        self.label_VSWR.setText(_translate("MainWindow", "2.3"))
        self.label_RFout_REF.setText(_translate("MainWindow", "0.4kW"))
        self.label_RFout_FOR.setText(_translate("MainWindow", "2.4kW"))
        self.label_FaultDetected.setText(_translate("MainWindow", "Fault detected"))
        self.pushButton_OP.setText(_translate("MainWindow", "STBY"))
        self.pushButton_PTT.setText(_translate("MainWindow", "PTT"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Fault Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Main), _translate("MainWindow", "   Main   "))
        self.label_5.setText(_translate("MainWindow", "REF"))
        self.label_6.setText(_translate("MainWindow", "FOR"))
        self.label_7.setText(_translate("MainWindow", "VSWR"))
        self.progressBar_ETA_Amp1.setFormat(_translate("MainWindow", "%p kW"))
        self.label_8.setText(_translate("MainWindow", "Temp"))
        self.progressBar_RFout_FOR_Amp1.setFormat(_translate("MainWindow", "%p kW"))
        self.label_VSWR_Amp1.setText(_translate("MainWindow", "2.3"))
        self.label_eta_Amp1.setText(_translate("MainWindow", "40degC"))
        self.label_RFout_REF_Amp1.setText(_translate("MainWindow", "0.4kW"))
        self.label_RFout_FOR_Amp1.setText(_translate("MainWindow", "2.4kW"))
        self.progressBar_VSWR_Amp1.setFormat(_translate("MainWindow", "%p kW"))
        self.progressBar_RFout_REF_Amp1.setFormat(_translate("MainWindow", "%p kW"))
        self.label_13.setText(_translate("MainWindow", "High VSWR"))
        self.label_14.setText(_translate("MainWindow", "Interlocks:"))
        self.label_16.setText(_translate("MainWindow", "High Temperature"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AMP1), _translate("MainWindow", "   AMP1   "))
        self.label_9.setText(_translate("MainWindow", "FOR"))
        self.label_10.setText(_translate("MainWindow", "VSWR"))
        self.label_eta_Amp1_2.setText(_translate("MainWindow", "50degC"))
        self.label_11.setText(_translate("MainWindow", "REF"))
        self.label_RFout_FOR_Amp1_2.setText(_translate("MainWindow", "2.4kW"))
        self.label_12.setText(_translate("MainWindow", "Temp"))
        self.progressBar_ETA_Amp1_2.setFormat(_translate("MainWindow", "%p kW"))
        self.progressBar_VSWR_Amp1_2.setFormat(_translate("MainWindow", "%p kW"))
        self.progressBar_RFout_FOR_Amp1_2.setFormat(_translate("MainWindow", "%p kW"))
        self.progressBar_RFout_REF_Amp1_2.setFormat(_translate("MainWindow", "%p kW"))
        self.label_VSWR_Amp1_2.setText(_translate("MainWindow", "2.3"))
        self.label_RFout_REF_Amp1_2.setText(_translate("MainWindow", "0.4kW"))
        self.label_19.setText(_translate("MainWindow", "High Temperature"))
        self.label_20.setText(_translate("MainWindow", "High VSWR"))
        self.label_21.setText(_translate("MainWindow", "Interlocks:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AMP2), _translate("MainWindow", "   AMP2   "))
        self.label_Amplifier_Hostname.setText(_translate("MainWindow", "Amplifier Hostname: "))
        self.label_Version.setText(_translate("MainWindow", "Version: "))
        self.pushButton_emulateFault.setText(_translate("MainWindow", "emulate fault"))
        self.label_25.setText(_translate("MainWindow", "High VDD"))
        self.label_26.setText(_translate("MainWindow", "High IDD"))
        self.label_27.setText(_translate("MainWindow", "RF input overload"))
        self.label_Version_2.setText(_translate("MainWindow", "Band Select:"))
        self.label_Version_3.setText(_translate("MainWindow", "Interlocks:"))
        self.label_Version_4.setText(_translate("MainWindow", "Antenna Select:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_System), _translate("MainWindow", "   System"))
        self.label_Status.setText(_translate("MainWindow", "Status Label"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
